# Generated by Django 3.0.8 on 2020-07-25 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Признак заказа')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название каталога')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название статьи')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок статьи')),
                ('text', models.TextField(max_length=200, verbose_name='Текст статьи')),
                ('order', models.IntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='SubCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название каталога')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('catalogs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Catalog')),
            ],
            options={
                'verbose_name': 'Подкаталог',
                'verbose_name_plural': 'Подкаталоги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_count', models.IntegerField(null=True, verbose_name='Количество товаров')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('cart', models.ManyToManyField(to='shop.Cart', verbose_name='Корзина')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название телефона')),
                ('image', models.FilePathField(path='static', verbose_name='Фотография телефона')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('catalogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Catalog')),
                ('papers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Paper')),
                ('sub_catalogs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.SubCatalog')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=40, null=True, verbose_name='Имя автора')),
                ('score', models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★', '★★★★'), ('★★★', '★★★'), ('★★', '★★'), ('★', '★')], max_length=10, null=True, verbose_name='Оценка')),
                ('description', models.TextField(max_length=200, verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('csrftoken', models.CharField(blank=True, max_length=200, null=True, verbose_name='CSRFTOKEN')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Good', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Good', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
