# Generated by Django 3.0.8 on 2020-07-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='catalogs',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='sub_catalogs',
            new_name='sub_catalog',
        ),
        migrations.RenameField(
            model_name='subcatalog',
            old_name='catalogs',
            new_name='catalog',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
