# Generated by Django 3.0.8 on 2020-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200728_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название товара'),
        ),
    ]
