# Generated by Django 3.0.8 on 2020-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods_price',
            field=models.IntegerField(null=True, verbose_name='Цена товаров'),
        ),
    ]
